using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing AggregateMetricData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AggregateMetricDataTests
    {
        private AggregateMetricData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AggregateMetricData();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of AggregateMetricData
        /// </summary>
        [Test]
        public void AggregateMetricDataInstanceTest()
        {
            Assert.IsInstanceOf<AggregateMetricData> (instance, "instance is a AggregateMetricData");
        }

        
        /// <summary>
        /// Test the property 'Metric' 
        /// </summary>
        [Test]
        public void MetricTest()
        {
            // TODO: unit test for the property 'Metric' 
        }
        
        /// <summary>
        /// Test the property 'Qualifier' 
        /// </summary>
        [Test]
        public void QualifierTest()
        {
            // TODO: unit test for the property 'Qualifier' 
        }
        
        /// <summary>
        /// Test the property 'Stats' 
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO: unit test for the property 'Stats' 
        }
        

    }

}
