using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing AggregationQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AggregationQueryTests
    {
        private AggregationQuery instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AggregationQuery();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AggregationQuery
        /// </summary>
        [Test]
        public void AggregationQueryInstanceTest()
        {
            Assert.IsInstanceOf<AggregationQuery> (instance, "instance is a AggregationQuery");
        }

        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Test]
        public void IntervalTest()
        {
            // TODO: unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'Granularity'
        /// </summary>
        [Test]
        public void GranularityTest()
        {
            // TODO: unit test for the property 'Granularity'
        }
        /// <summary>
        /// Test the property 'GroupBy'
        /// </summary>
        [Test]
        public void GroupByTest()
        {
            // TODO: unit test for the property 'GroupBy'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO: unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Test]
        public void MetricsTest()
        {
            // TODO: unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'FlattenMultivaluedDimensions'
        /// </summary>
        [Test]
        public void FlattenMultivaluedDimensionsTest()
        {
            // TODO: unit test for the property 'FlattenMultivaluedDimensions'
        }

    }

}
