using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing AnalyticsSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalyticsSessionTests
    {
        private AnalyticsSession instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnalyticsSession();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalyticsSession
        /// </summary>
        [Test]
        public void AnalyticsSessionInstanceTest()
        {
            Assert.IsInstanceOf<AnalyticsSession> (instance, "instance is a AnalyticsSession");
        }

        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Test]
        public void MediaTypeTest()
        {
            // TODO: unit test for the property 'MediaType'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO: unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'AddressOther'
        /// </summary>
        [Test]
        public void AddressOtherTest()
        {
            // TODO: unit test for the property 'AddressOther'
        }
        /// <summary>
        /// Test the property 'AddressSelf'
        /// </summary>
        [Test]
        public void AddressSelfTest()
        {
            // TODO: unit test for the property 'AddressSelf'
        }
        /// <summary>
        /// Test the property 'Ani'
        /// </summary>
        [Test]
        public void AniTest()
        {
            // TODO: unit test for the property 'Ani'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO: unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'Dnis'
        /// </summary>
        [Test]
        public void DnisTest()
        {
            // TODO: unit test for the property 'Dnis'
        }
        /// <summary>
        /// Test the property 'OutboundCampaignId'
        /// </summary>
        [Test]
        public void OutboundCampaignIdTest()
        {
            // TODO: unit test for the property 'OutboundCampaignId'
        }
        /// <summary>
        /// Test the property 'OutboundContactListId'
        /// </summary>
        [Test]
        public void OutboundContactListIdTest()
        {
            // TODO: unit test for the property 'OutboundContactListId'
        }
        /// <summary>
        /// Test the property 'DispositionAnalyzer'
        /// </summary>
        [Test]
        public void DispositionAnalyzerTest()
        {
            // TODO: unit test for the property 'DispositionAnalyzer'
        }
        /// <summary>
        /// Test the property 'DispositionName'
        /// </summary>
        [Test]
        public void DispositionNameTest()
        {
            // TODO: unit test for the property 'DispositionName'
        }
        /// <summary>
        /// Test the property 'EdgeId'
        /// </summary>
        [Test]
        public void EdgeIdTest()
        {
            // TODO: unit test for the property 'EdgeId'
        }
        /// <summary>
        /// Test the property 'RemoteNameDisplayable'
        /// </summary>
        [Test]
        public void RemoteNameDisplayableTest()
        {
            // TODO: unit test for the property 'RemoteNameDisplayable'
        }
        /// <summary>
        /// Test the property 'RoomId'
        /// </summary>
        [Test]
        public void RoomIdTest()
        {
            // TODO: unit test for the property 'RoomId'
        }
        /// <summary>
        /// Test the property 'MonitoredSessionId'
        /// </summary>
        [Test]
        public void MonitoredSessionIdTest()
        {
            // TODO: unit test for the property 'MonitoredSessionId'
        }
        /// <summary>
        /// Test the property 'MonitoredParticipantId'
        /// </summary>
        [Test]
        public void MonitoredParticipantIdTest()
        {
            // TODO: unit test for the property 'MonitoredParticipantId'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Test]
        public void SegmentsTest()
        {
            // TODO: unit test for the property 'Segments'
        }

    }

}
