using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing ExternalOrganization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalOrganizationTests
    {
        private ExternalOrganization instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExternalOrganization();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalOrganization
        /// </summary>
        [Test]
        public void ExternalOrganizationInstanceTest()
        {
            Assert.IsInstanceOf<ExternalOrganization> (instance, "instance is a ExternalOrganization");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CompanyType'
        /// </summary>
        [Test]
        public void CompanyTypeTest()
        {
            // TODO: unit test for the property 'CompanyType'
        }
        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Test]
        public void IndustryTest()
        {
            // TODO: unit test for the property 'Industry'
        }
        /// <summary>
        /// Test the property 'PrimaryContactId'
        /// </summary>
        [Test]
        public void PrimaryContactIdTest()
        {
            // TODO: unit test for the property 'PrimaryContactId'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO: unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'FaxNumber'
        /// </summary>
        [Test]
        public void FaxNumberTest()
        {
            // TODO: unit test for the property 'FaxNumber'
        }
        /// <summary>
        /// Test the property 'EmployeeCount'
        /// </summary>
        [Test]
        public void EmployeeCountTest()
        {
            // TODO: unit test for the property 'EmployeeCount'
        }
        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Test]
        public void RevenueTest()
        {
            // TODO: unit test for the property 'Revenue'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO: unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Websites'
        /// </summary>
        [Test]
        public void WebsitesTest()
        {
            // TODO: unit test for the property 'Websites'
        }
        /// <summary>
        /// Test the property 'Tickers'
        /// </summary>
        [Test]
        public void TickersTest()
        {
            // TODO: unit test for the property 'Tickers'
        }
        /// <summary>
        /// Test the property 'ModifyDate'
        /// </summary>
        [Test]
        public void ModifyDateTest()
        {
            // TODO: unit test for the property 'ModifyDate'
        }
        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Test]
        public void CreateDateTest()
        {
            // TODO: unit test for the property 'CreateDate'
        }
        /// <summary>
        /// Test the property 'ExternalDataSources'
        /// </summary>
        [Test]
        public void ExternalDataSourcesTest()
        {
            // TODO: unit test for the property 'ExternalDataSources'
        }
        /// <summary>
        /// Test the property 'SelfUri'
        /// </summary>
        [Test]
        public void SelfUriTest()
        {
            // TODO: unit test for the property 'SelfUri'
        }

    }

}
