using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing FlowVersionConfigMetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowVersionConfigMetaDataTests
    {
        private FlowVersionConfigMetaData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FlowVersionConfigMetaData();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of FlowVersionConfigMetaData
        /// </summary>
        [Test]
        public void FlowVersionConfigMetaDataInstanceTest()
        {
            Assert.IsInstanceOf<FlowVersionConfigMetaData> (instance, "instance is a FlowVersionConfigMetaData");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'VersionSpecificComment' 
        /// </summary>
        [Test]
        public void VersionSpecificCommentTest()
        {
            // TODO: unit test for the property 'VersionSpecificComment' 
        }
        
        /// <summary>
        /// Test the property 'FlowDefinitionUri' 
        /// </summary>
        [Test]
        public void FlowDefinitionUriTest()
        {
            // TODO: unit test for the property 'FlowDefinitionUri' 
        }
        
        /// <summary>
        /// Test the property 'CreatedByUser' 
        /// </summary>
        [Test]
        public void CreatedByUserTest()
        {
            // TODO: unit test for the property 'CreatedByUser' 
        }
        
        /// <summary>
        /// Test the property 'CreatedDate' 
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO: unit test for the property 'CreatedDate' 
        }
        
        /// <summary>
        /// Test the property 'SelfUri' 
        /// </summary>
        [Test]
        public void SelfUriTest()
        {
            // TODO: unit test for the property 'SelfUri' 
        }
        
        /// <summary>
        /// Test the property 'Version' 
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO: unit test for the property 'Version' 
        }
        

    }

}
