using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing FlowDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowDetailsTests
    {
        private FlowDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FlowDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowDetails
        /// </summary>
        [Test]
        public void FlowDetailsInstanceTest()
        {
            Assert.IsInstanceOf<FlowDetails> (instance, "instance is a FlowDetails");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FlowConfigId'
        /// </summary>
        [Test]
        public void FlowConfigIdTest()
        {
            // TODO: unit test for the property 'FlowConfigId'
        }
        /// <summary>
        /// Test the property 'LaunchTime'
        /// </summary>
        [Test]
        public void LaunchTimeTest()
        {
            // TODO: unit test for the property 'LaunchTime'
        }
        /// <summary>
        /// Test the property 'LaunchType'
        /// </summary>
        [Test]
        public void LaunchTypeTest()
        {
            // TODO: unit test for the property 'LaunchType'
        }
        /// <summary>
        /// Test the property 'LaunchedBy'
        /// </summary>
        [Test]
        public void LaunchedByTest()
        {
            // TODO: unit test for the property 'LaunchedBy'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'AssociatedDocuments'
        /// </summary>
        [Test]
        public void AssociatedDocumentsTest()
        {
            // TODO: unit test for the property 'AssociatedDocuments'
        }
        /// <summary>
        /// Test the property 'FlowCompletionTime'
        /// </summary>
        [Test]
        public void FlowCompletionTimeTest()
        {
            // TODO: unit test for the property 'FlowCompletionTime'
        }
        /// <summary>
        /// Test the property 'FlowCompletionReason'
        /// </summary>
        [Test]
        public void FlowCompletionReasonTest()
        {
            // TODO: unit test for the property 'FlowCompletionReason'
        }
        /// <summary>
        /// Test the property 'FlowErrorInfo'
        /// </summary>
        [Test]
        public void FlowErrorInfoTest()
        {
            // TODO: unit test for the property 'FlowErrorInfo'
        }
        /// <summary>
        /// Test the property 'SelfUri'
        /// </summary>
        [Test]
        public void SelfUriTest()
        {
            // TODO: unit test for the property 'SelfUri'
        }

    }

}
