using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing InteractionStatsAlert
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InteractionStatsAlertTests
    {
        private InteractionStatsAlert instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InteractionStatsAlert();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of InteractionStatsAlert
        /// </summary>
        [Test]
        public void InteractionStatsAlertInstanceTest()
        {
            Assert.IsInstanceOf<InteractionStatsAlert> (instance, "instance is a InteractionStatsAlert");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'Dimension' 
        /// </summary>
        [Test]
        public void DimensionTest()
        {
            // TODO: unit test for the property 'Dimension' 
        }
        
        /// <summary>
        /// Test the property 'DimensionValue' 
        /// </summary>
        [Test]
        public void DimensionValueTest()
        {
            // TODO: unit test for the property 'DimensionValue' 
        }
        
        /// <summary>
        /// Test the property 'Metric' 
        /// </summary>
        [Test]
        public void MetricTest()
        {
            // TODO: unit test for the property 'Metric' 
        }
        
        /// <summary>
        /// Test the property 'MediaType' 
        /// </summary>
        [Test]
        public void MediaTypeTest()
        {
            // TODO: unit test for the property 'MediaType' 
        }
        
        /// <summary>
        /// Test the property 'NumericRange' 
        /// </summary>
        [Test]
        public void NumericRangeTest()
        {
            // TODO: unit test for the property 'NumericRange' 
        }
        
        /// <summary>
        /// Test the property 'Statistic' 
        /// </summary>
        [Test]
        public void StatisticTest()
        {
            // TODO: unit test for the property 'Statistic' 
        }
        
        /// <summary>
        /// Test the property 'Value' 
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO: unit test for the property 'Value' 
        }
        
        /// <summary>
        /// Test the property 'RuleId' 
        /// </summary>
        [Test]
        public void RuleIdTest()
        {
            // TODO: unit test for the property 'RuleId' 
        }
        
        /// <summary>
        /// Test the property 'Unread' 
        /// </summary>
        [Test]
        public void UnreadTest()
        {
            // TODO: unit test for the property 'Unread' 
        }
        
        /// <summary>
        /// Test the property 'StartDate' 
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO: unit test for the property 'StartDate' 
        }
        
        /// <summary>
        /// Test the property 'EndDate' 
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO: unit test for the property 'EndDate' 
        }
        
        /// <summary>
        /// Test the property 'NotificationUsers' 
        /// </summary>
        [Test]
        public void NotificationUsersTest()
        {
            // TODO: unit test for the property 'NotificationUsers' 
        }
        
        /// <summary>
        /// Test the property 'AlertTypes' 
        /// </summary>
        [Test]
        public void AlertTypesTest()
        {
            // TODO: unit test for the property 'AlertTypes' 
        }
        
        /// <summary>
        /// Test the property 'RuleUri' 
        /// </summary>
        [Test]
        public void RuleUriTest()
        {
            // TODO: unit test for the property 'RuleUri' 
        }
        
        /// <summary>
        /// Test the property 'SelfUri' 
        /// </summary>
        [Test]
        public void SelfUriTest()
        {
            // TODO: unit test for the property 'SelfUri' 
        }
        

    }

}
