using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing NumericRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NumericRangeTests
    {
        private NumericRange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NumericRange();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of NumericRange
        /// </summary>
        [Test]
        public void NumericRangeInstanceTest()
        {
            Assert.IsInstanceOf<NumericRange> (instance, "instance is a NumericRange");
        }

        
        /// <summary>
        /// Test the property 'Gt' 
        /// </summary>
        [Test]
        public void GtTest()
        {
            // TODO: unit test for the property 'Gt' 
        }
        
        /// <summary>
        /// Test the property 'Gte' 
        /// </summary>
        [Test]
        public void GteTest()
        {
            // TODO: unit test for the property 'Gte' 
        }
        
        /// <summary>
        /// Test the property 'Lt' 
        /// </summary>
        [Test]
        public void LtTest()
        {
            // TODO: unit test for the property 'Lt' 
        }
        
        /// <summary>
        /// Test the property 'Lte' 
        /// </summary>
        [Test]
        public void LteTest()
        {
            // TODO: unit test for the property 'Lte' 
        }
        

    }

}
