using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing PresenceQueryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PresenceQueryResponseTests
    {
        private PresenceQueryResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PresenceQueryResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PresenceQueryResponse
        /// </summary>
        [Test]
        public void PresenceQueryResponseInstanceTest()
        {
            Assert.IsInstanceOf<PresenceQueryResponse> (instance, "instance is a PresenceQueryResponse");
        }

        /// <summary>
        /// Test the property 'SystemToOrganizationMappings'
        /// </summary>
        [Test]
        public void SystemToOrganizationMappingsTest()
        {
            // TODO: unit test for the property 'SystemToOrganizationMappings'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO: unit test for the property 'Results'
        }

    }

}
