using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing PropertyIndexRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PropertyIndexRequestTests
    {
        private PropertyIndexRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PropertyIndexRequest();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PropertyIndexRequest
        /// </summary>
        [Test]
        public void PropertyIndexRequestInstanceTest()
        {
            Assert.IsInstanceOf<PropertyIndexRequest> (instance, "instance is a PropertyIndexRequest");
        }

        
        /// <summary>
        /// Test the property 'SessionId' 
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO: unit test for the property 'SessionId' 
        }
        
        /// <summary>
        /// Test the property 'Timestamp' 
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO: unit test for the property 'Timestamp' 
        }
        
        /// <summary>
        /// Test the property 'Properties' 
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO: unit test for the property 'Properties' 
        }
        

    }

}
