using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ININ.PureCloudApi.Client;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SearchApiTests
    {
        private SearchApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
           instance = new SearchApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf<SearchApi> (instance, "instance is a SearchApi");
        }

        
        /// <summary>
        /// Test GetSearch
        /// </summary>
        [Test]
        public void GetSearchTest()
        {
            // TODO: add unit test for the method 'GetSearch'
            string q64 = null; // TODO: replace null with proper value
            List<string> expand = null; // TODO: replace null with proper value
            var response = instance.GetSearch(q64, expand);
            Assert.IsInstanceOf<GroupsSearchResponse> (response, "response is GroupsSearchResponse");
        }
        
        /// <summary>
        /// Test GetSearch_0
        /// </summary>
        [Test]
        public void GetSearch_0Test()
        {
            // TODO: add unit test for the method 'GetSearch_0'
            string q64 = null; // TODO: replace null with proper value
            List<string> expand = null; // TODO: replace null with proper value
            var response = instance.GetSearch_0(q64, expand);
            Assert.IsInstanceOf<JsonNodeSearchResponse> (response, "response is JsonNodeSearchResponse");
        }
        
        /// <summary>
        /// Test GetSearch_1
        /// </summary>
        [Test]
        public void GetSearch_1Test()
        {
            // TODO: add unit test for the method 'GetSearch_1'
            string q64 = null; // TODO: replace null with proper value
            List<string> expand = null; // TODO: replace null with proper value
            var response = instance.GetSearch_1(q64, expand);
            Assert.IsInstanceOf<UsersSearchResponse> (response, "response is UsersSearchResponse");
        }
        
        /// <summary>
        /// Test PostSearch
        /// </summary>
        [Test]
        public void PostSearchTest()
        {
            // TODO: add unit test for the method 'PostSearch'
            SearchRequest body = null; // TODO: replace null with proper value
            var response = instance.PostSearch(body);
            Assert.IsInstanceOf<GroupsSearchResponse> (response, "response is GroupsSearchResponse");
        }
        
        /// <summary>
        /// Test PostSearch_0
        /// </summary>
        [Test]
        public void PostSearch_0Test()
        {
            // TODO: add unit test for the method 'PostSearch_0'
            SearchRequest body = null; // TODO: replace null with proper value
            var response = instance.PostSearch_0(body);
            Assert.IsInstanceOf<JsonNodeSearchResponse> (response, "response is JsonNodeSearchResponse");
        }
        
        /// <summary>
        /// Test PostSearch_1
        /// </summary>
        [Test]
        public void PostSearch_1Test()
        {
            // TODO: add unit test for the method 'PostSearch_1'
            SearchRequest body = null; // TODO: replace null with proper value
            var response = instance.PostSearch_1(body);
            Assert.IsInstanceOf<UsersSearchResponse> (response, "response is UsersSearchResponse");
        }
        
    }

}
