using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ININ.PureCloudApi.Api;
using ININ.PureCloudApi.Model;
using ININ.PureCloudApi.Client;
using System.Reflection;

namespace ININ.PureCloudApi.Test
{
    /// <summary>
    ///  Class for testing SpreadsheetTransform
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpreadsheetTransformTests
    {
        private SpreadsheetTransform instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpreadsheetTransform();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of SpreadsheetTransform
        /// </summary>
        [Test]
        public void SpreadsheetTransformInstanceTest()
        {
            Assert.IsInstanceOf<SpreadsheetTransform> (instance, "instance is a SpreadsheetTransform");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'RestEndpoint' 
        /// </summary>
        [Test]
        public void RestEndpointTest()
        {
            // TODO: unit test for the property 'RestEndpoint' 
        }
        
        /// <summary>
        /// Test the property 'FilenameTransforms' 
        /// </summary>
        [Test]
        public void FilenameTransformsTest()
        {
            // TODO: unit test for the property 'FilenameTransforms' 
        }
        
        /// <summary>
        /// Test the property 'Tags' 
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO: unit test for the property 'Tags' 
        }
        
        /// <summary>
        /// Test the property 'SheetNameTransforms' 
        /// </summary>
        [Test]
        public void SheetNameTransformsTest()
        {
            // TODO: unit test for the property 'SheetNameTransforms' 
        }
        
        /// <summary>
        /// Test the property 'Sheets' 
        /// </summary>
        [Test]
        public void SheetsTest()
        {
            // TODO: unit test for the property 'Sheets' 
        }
        
        /// <summary>
        /// Test the property 'ClientTransformModel' 
        /// </summary>
        [Test]
        public void ClientTransformModelTest()
        {
            // TODO: unit test for the property 'ClientTransformModel' 
        }
        
        /// <summary>
        /// Test the property 'SelfUri' 
        /// </summary>
        [Test]
        public void SelfUriTest()
        {
            // TODO: unit test for the property 'SelfUri' 
        }
        

    }

}
